version: '3'

services:

  spark:
    build: ./spark
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8081:8080
      - 7077:7077
    volumes:
      - ./spark/jars:/spark_jobs
    extra_hosts:
      - "presto postgres-data postgres-data-dba namenode-dba datanode-dba:192.168.1.98"

  spark-worker:
    build: ./spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark/jars:/spark_jobs
    extra_hosts:
      - "presto postgres-data postgres-data-dba namenode-dba datanode-dba:192.168.1.98"
    depends_on:
      - spark
  