version: '3'

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - ./datas/hive/hdfs/namenode:/hadoop/dfs/name
      - ./hadoop/upload_files:/upload_files
    environment:
      - CLUSTER_NAME=hive
    env_file:
      - ./hive/hadoop-hive.env
    ports:
      - 9870:9870
      - 9000:9000

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    volumes:
      - ./datas/hive/hdfs/datanode:/hadoop/dfs/data
    env_file:
      - ./hive/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode
    ports:
      - 9866:9866
      - 9864:9864

  postgres-data:
    image: postgres:latest
    container_name: postgres-data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./datas/postgre:/var/lib/postgresql/data
      # copy the sql script to create tables
      - .postgre-data/sql/:/docker-entrypoint-initdb.d/
  